# https://cli.vuejs.org/guide/deployment.html#gitlab-pages

# https://hub.docker.com/_/node/
image: node:latest

stages:
  - Yarn

#cache:
#  paths:
#    - node_modules/

"Yarn Install":
  stage: Yarn
  script:
    - npm install
  cache:
    key: "${CI_PROJECT_ID}_cache_yarn"
    paths:
      - .yarn-cache/
      - node_modules/
